/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project.org.jcae.netbeans.of.actions;

import java.text.DecimalFormat;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.netbeans.api.project.Project;
import project.org.jcae.netbeans.of.project.ProjectGeomUtils;
import project.org.jcae.netbeans.of.project.ProjectUtils;

/**
 *
 * @author mohit
 */
public class BGBlockPanel extends javax.swing.JPanel {

    /**
     * Creates new form BGBlockPanel
     */
    String rName;
    String sName;
    Project pr;
    
    private BGBlock blockParams;
    
    public BGBlockPanel(String rName,String sName, Project pr) {
        this.rName = rName;
        this.sName = sName;
        this.pr = pr;
        //blockParams = new BGBlock();
        initComponents();
        
        loadPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfUX = new javax.swing.JTextField();
        jtfUY = new javax.swing.JTextField();
        jtfUZ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfLX = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfLY = new javax.swing.JTextField();
        jtfLZ = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfRX = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfRY = new javax.swing.JTextField();
        jtfRZ = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfGradeY = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtfGradeX = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfGradeZ = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel3.text")); // NOI18N

        jtfUX.setText(org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jtfUX.text")); // NOI18N

        jtfUY.setText(org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jtfUY.text")); // NOI18N

        jtfUZ.setText(org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jtfUZ.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel4.text")); // NOI18N

        jtfLX.setText(org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jtfLX.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel6.text")); // NOI18N

        jtfLY.setText(org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jtfLY.text")); // NOI18N

        jtfLZ.setText(org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jtfLZ.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel7.text")); // NOI18N

        jtfRX.setText(org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jtfRX.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel8.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel9.text")); // NOI18N

        jtfRY.setText(org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jtfRY.text")); // NOI18N

        jtfRZ.setText(org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jtfRZ.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel10.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel11.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel12.text")); // NOI18N

        jtfGradeY.setText(org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jtfGradeY.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel13, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel13.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel14, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel14.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel15, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel15.text")); // NOI18N

        jtfGradeX.setText(org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jtfGradeX.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel16, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jLabel16.text")); // NOI18N

        jtfGradeZ.setText(org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jtfGradeZ.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, org.openide.util.NbBundle.getMessage(BGBlockPanel.class, "BGBlockPanel.jCheckBox1.text")); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel12))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(13, 13, 13)
                                                .addComponent(jtfRX, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtfRY, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel7))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(13, 13, 13)
                                                .addComponent(jtfGradeX, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtfGradeY, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel14)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfGradeZ, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfRZ, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(3, 3, 3)
                                        .addComponent(jtfLX, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfLY, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfLZ, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(3, 3, 3)
                                .addComponent(jtfUX, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfUY, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfUZ, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jCheckBox1)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jtfUX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jtfLX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jtfRX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jtfGradeX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfGradeY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfGradeZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        // 1. Get all patches
        // 2. Get bounding box of all patches
        // 3. For each bounding box, create a global boounding box
        if(jCheckBox1.isSelected())
        {
            double[] globalBB = ProjectGeomUtils.getBoundingBox(sName,rName,pr.getProjectDirectory());
            DecimalFormat f = new DecimalFormat("##.00");        
            jtfLX.setText( f.format(globalBB[0]));
            jtfLY.setText( f.format(globalBB[1]));
            jtfLZ.setText( f.format(globalBB[2]));

            jtfUX.setText( f.format(globalBB[3]));
            jtfUY.setText( f.format(globalBB[4]));
            jtfUZ.setText( f.format(globalBB[5]));
        }
        else
        {
            jtfLX.setText(blockParams.getlBounds()[0]);
            jtfLY.setText(blockParams.getlBounds()[1]);
            jtfLZ.setText(blockParams.getlBounds()[2]);

            jtfUX.setText(blockParams.getuBounds()[0]);
            jtfUY.setText(blockParams.getuBounds()[1]);
            jtfUZ.setText(blockParams.getuBounds()[2]);            
        }            
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jtfGradeX;
    private javax.swing.JTextField jtfGradeY;
    private javax.swing.JTextField jtfGradeZ;
    private javax.swing.JTextField jtfLX;
    private javax.swing.JTextField jtfLY;
    private javax.swing.JTextField jtfLZ;
    private javax.swing.JTextField jtfRX;
    private javax.swing.JTextField jtfRY;
    private javax.swing.JTextField jtfRZ;
    private javax.swing.JTextField jtfUX;
    private javax.swing.JTextField jtfUY;
    private javax.swing.JTextField jtfUZ;
    // End of variables declaration//GEN-END:variables

    public void loadPanel() 
    {
        // 1. Lookout for BGBlock tag in Region->SubRegion, if not found createa  new one from MasterBlockmesh.xml
        blockParams = ProjectUtils.getBlockmeshInSubRegion(rName, sName, pr.getProjectDirectory());
        
        // 2. Load UBound, LBound, Resolution and Grading params to the panel
        jtfLX.setText(blockParams.getlBounds()[0]);
        jtfLY.setText(blockParams.getlBounds()[1]);
        jtfLZ.setText(blockParams.getlBounds()[2]);

        jtfUX.setText(blockParams.getuBounds()[0]);
        jtfUY.setText(blockParams.getuBounds()[1]);
        jtfUZ.setText(blockParams.getuBounds()[2]);
        
        jtfRX.setText(blockParams.getResolution()[0]);
        jtfRY.setText(blockParams.getResolution()[1]);
        jtfRZ.setText(blockParams.getResolution()[2]);
        
        jtfGradeX.setText(blockParams.getSimpleGrading()[0]);
        jtfGradeY.setText(blockParams.getSimpleGrading()[1]);
        jtfGradeZ.setText(blockParams.getSimpleGrading()[2]);
        
        // 3. Modify BlockMesh tag accordingly in Project.xml
        // 4. Update BGPatchNodes in Project.xml
        // 5. Load Project Node structure.
        // Steps 3,4,5 - Done on GenerateBlockMeshAction performedAction()
    }
    
    public boolean showDialog()
    {
        final JOptionPane jp = new JOptionPane(this,JOptionPane.PLAIN_MESSAGE, JOptionPane.OK_CANCEL_OPTION);
        JDialog d = jp.createDialog("Block Mesh Options - "+sName);
        d.setResizable(true);
        d.setVisible(true);
        return Integer.valueOf(JOptionPane.OK_OPTION).equals(jp.getValue());
    }
    
    public BGBlock getBGBlock()
    {
        if(validateAll())
        {
            blockParams.getlBounds()[0] = jtfLX.getText();
            blockParams.getlBounds()[1] = jtfLY.getText();
            blockParams.getlBounds()[2] = jtfLZ.getText();

            blockParams.getuBounds()[0] = jtfUX.getText();
            blockParams.getuBounds()[1] = jtfUY.getText();
            blockParams.getuBounds()[2] = jtfUZ.getText();
            
            blockParams.getResolution()[0] = jtfRX.getText();
            blockParams.getResolution()[1] = jtfRY.getText();
            blockParams.getResolution()[2] = jtfRZ.getText();
            
            blockParams.getSimpleGrading()[0] = jtfGradeX.getText();
            blockParams.getSimpleGrading()[1] = jtfGradeY.getText();
            blockParams.getSimpleGrading()[2] = jtfGradeZ.getText();
            
        }
        return blockParams;
    }
    
    private boolean validateAll()
    {
        if(validate(jtfLX) && validate(jtfLY) && validate(jtfLZ) && 
            validate(jtfUX) && validate(jtfUY) && validate(jtfUZ) &&
            validate(jtfRX) && validate(jtfRY) && validate(jtfRZ) &&
            validate(jtfGradeX) && validate(jtfGradeY) && validate(jtfGradeZ))
        {
            if(validateLowerUpper())
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        else
        {
            return false;
        }
    }
    
    private boolean validate(JTextField jtf)
    {
        boolean flag = false;
        try {
            Double.parseDouble(jtf.getText());
            flag = true;
        }
        catch(NumberFormatException ex) {            
        }        
        return flag;        
    }

    private boolean validateLowerUpper() 
    {
        if( ( Double.parseDouble(jtfUX.getText()) - Double.parseDouble(jtfLX.getText()) ) > 0 && 
                ( Double.parseDouble(jtfUY.getText()) - Double.parseDouble(jtfLY.getText()) ) > 0 && 
                ( Double.parseDouble(jtfUZ.getText()) - Double.parseDouble(jtfLZ.getText()) ) > 0 )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    
    public static class BGBlock
    {
        private String[] uBounds = new String[3];
        private String[] lBounds = new String[3];
        private String[] resolution = new String[3];
        private String[] simpleGrading = new String[3];

        /**
         * @return the uBounds
         */
        public String[] getuBounds() {
            return uBounds;
        }

        /**
         * @param uBounds the uBounds to set
         */
        public void setuBounds(String[] uBounds) {
            this.uBounds = uBounds;
        }

        /**
         * @return the lBounds
         */
        public String[] getlBounds() {
            return lBounds;
        }

        /**
         * @param lBounds the lBounds to set
         */
        public void setlBounds(String[] lBounds) {
            this.lBounds = lBounds;
        }

        /**
         * @return the resolution
         */
        public String[] getResolution() {
            return resolution;
        }

        /**
         * @param resolution the resolution to set
         */
        public void setResolution(String[] resolution) {
            this.resolution = resolution;
        }

        /**
         * @return the simpleGrading
         */
        public String[] getSimpleGrading() {
            return simpleGrading;
        }

        /**
         * @param simpleGrading the simpleGrading to set
         */
        public void setSimpleGrading(String[] simpleGrading) {
            this.simpleGrading = simpleGrading;
        }
    }
}
