/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project.org.jcae.netbeans.of.actions;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.netbeans.api.project.Project;
import project.org.jcae.netbeans.of.project.ProjectUtils;

/**
 *
 * @author mohit
 */
public class CellZonePanel extends javax.swing.JPanel 
{

    String regionName;
    Project project;
    
    CZParams params;

    
    /**
     * Creates new form CellZonePanel
     */
    public CellZonePanel(String rName, Project pr) 
    {
        initComponents();
        regionName = rName;
        project = pr;
        
        params = new CZParams();
    }


    public boolean showDialog()
    {
        final JOptionPane jp = new JOptionPane(this,JOptionPane.PLAIN_MESSAGE, JOptionPane.OK_CANCEL_OPTION);        
        JDialog d = jp.createDialog("CellZone ");
        d.setResizable(true);
        d.setVisible(true);
        return Integer.valueOf(JOptionPane.OK_OPTION).equals(jp.getValue());
    }  
    
    private void loadParams()
    {
        String[] lowerBound = new String[3];
        lowerBound[0] = jTFLowerX.getText();
        lowerBound[1] = jTFLowerY.getText();
        lowerBound[2] = jTFLowerZ.getText();
        
        String[] upperBound = new String[3];
        upperBound[0] = jTFUpperX.getText();
        upperBound[1] = jTFUpperX.getText();
        upperBound[2] = jTFUpperX.getText();
        
        params.setLower(lowerBound);
        params.setUpper(upperBound);
        params.setZoneName(jTFZName.getText());
        
        
    }
    
    public void save()
    {
        loadParams();
        ProjectUtils.addCellZoneElement(regionName, params.getZoneName(), params.lower, params.getUpper(), project.getProjectDirectory());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTFZName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFUpperX = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTFUpperZ = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFLowerX = new javax.swing.JTextField();
        jTFLowerY = new javax.swing.JTextField();
        jTFLowerZ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCBType = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CellZonePanel.class, "CellZonePanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CellZonePanel.class, "CellZonePanel.jLabel1.text")); // NOI18N

        jTFZName.setText(org.openide.util.NbBundle.getMessage(CellZonePanel.class, "CellZonePanel.jTFZName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(CellZonePanel.class, "CellZonePanel.jLabel2.text")); // NOI18N

        jTFUpperX.setText(org.openide.util.NbBundle.getMessage(CellZonePanel.class, "CellZonePanel.jTFUpperX.text")); // NOI18N

        jTextField3.setText(org.openide.util.NbBundle.getMessage(CellZonePanel.class, "CellZonePanel.jTextField3.text")); // NOI18N

        jTFUpperZ.setText(org.openide.util.NbBundle.getMessage(CellZonePanel.class, "CellZonePanel.jTFUpperZ.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(CellZonePanel.class, "CellZonePanel.jLabel3.text")); // NOI18N

        jTFLowerX.setText(org.openide.util.NbBundle.getMessage(CellZonePanel.class, "CellZonePanel.jTFLowerX.text")); // NOI18N

        jTFLowerY.setText(org.openide.util.NbBundle.getMessage(CellZonePanel.class, "CellZonePanel.jTFLowerY.text")); // NOI18N

        jTFLowerZ.setText(org.openide.util.NbBundle.getMessage(CellZonePanel.class, "CellZonePanel.jTFLowerZ.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(CellZonePanel.class, "CellZonePanel.jLabel4.text")); // NOI18N

        jCBType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Box" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFLowerX, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFLowerY))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFUpperX, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFUpperZ)
                            .addComponent(jTFLowerZ, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFZName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCBType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFZName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFUpperX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFUpperZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFLowerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFLowerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFLowerZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCBType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTFLowerX;
    private javax.swing.JTextField jTFLowerY;
    private javax.swing.JTextField jTFLowerZ;
    private javax.swing.JTextField jTFUpperX;
    private javax.swing.JTextField jTFUpperZ;
    private javax.swing.JTextField jTFZName;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    public static class CZParams
    {
        private String zoneName;
        private String[] upper;
        private String[] lower;

        /**
         * @return the zoneName
         */
        public String getZoneName() {
            return zoneName;
        }

        /**
         * @param zoneName the zoneName to set
         */
        public void setZoneName(String zoneName) {
            this.zoneName = zoneName;
        }

        /**
         * @return the upper
         */
        public String[] getUpper() {
            return upper;
        }

        /**
         * @param upper the upper to set
         */
        public void setUpper(String[] upper) {
            this.upper = upper;
        }

        /**
         * @return the lower
         */
        public String[] getLower() {
            return lower;
        }

        /**
         * @param lower the lower to set
         */
        public void setLower(String[] lower) {
            this.lower = lower;
        }
    }
}
