/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project.org.jcae.netbeans.of.actions;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.openide.filesystems.FileObject;
import project.org.jcae.netbeans.of.project.ProjectFileUtils;
import project.org.jcae.netbeans.of.project.ProjectUtils;

/**
 *
 * @author mohit
 */
public class RegionSolidConstantSettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegionSolidConstantSettingsPanel
     */
    
    String regionName;
    FileObject project;
    
    public RegionSolidConstantSettingsPanel(String regionName, FileObject project) 
    {
        initComponents();
        this.regionName = regionName;
        this.project = project;       
    }
    
    public boolean showDialog()
    {
        final JOptionPane jp = new JOptionPane(this,JOptionPane.PLAIN_MESSAGE, JOptionPane.OK_CANCEL_OPTION);
        //JDialog j = new JDialog
        load();
        JDialog d = jp.createDialog("SnappyHexMesh ");
        d.setResizable(true);
        d.setVisible(true);
        return Integer.valueOf(JOptionPane.OK_OPTION).equals(jp.getValue());
    }
    
    public void load()
    {
        // Get settings file and load file data
        jTAThermal.setText(ProjectUtils.readFile(project.getPath() + "/" + regionName + "/constant/" + "thermalProperties" ));
    }
    
    public void save()
    {
        ProjectFileUtils.writeFile(jTAThermal.getText(), project.getPath() + "/" + regionName + "/constant/" + "thermalProperties" );        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAThermal = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 700));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTAThermal.setColumns(20);
        jTAThermal.setRows(5);
        jScrollPane1.setViewportView(jTAThermal);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(RegionSolidConstantSettingsPanel.class, "RegionSolidConstantSettingsPanel.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAThermal;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
