/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project.org.jcae.netbeans.of.options;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import org.netbeans.api.project.Project;
import project.org.jcae.netbeans.of.api.ofProp;
import project.org.jcae.netbeans.of.nodes.PatchNode;
import project.org.jcae.netbeans.of.project.ProjectUtils;

/**
 *
 * @author mita
 */
public class PatchFieldInfo extends javax.swing.JPanel 
{
    public class SubPanel extends JPanel 
    {        
        public SubPanel()
        {           
            //setBackground(Color.white);
            setBorder(BorderFactory.createTitledBorder("Properties")); 
        }
        
        public void initComponents() 
        {
            Collection<ofProp> collProp = ProjectUtils.getFieldPatchTypeProperties(patchSelected, pNode, pr.getProjectDirectory());
            
            // Create panel based on collProp
            if(collProp!=null)
            {
                setLayout(new GridLayout(collProp.size(), 1));
                
                for(int i=0;i<collProp.size();i++)
                {
                    ofProp ofProp = ((ArrayList<ofProp>) collProp).get(i);
                    add(ofProp.loadGraphics());
//                    if(ofProp instanceof Property)
//                    {
//                        Property p = (Property) ofProp;
//                        JLabel label = new JLabel(p.getKey());
//                        //label.setVisible(true);
//                        add(label);
//                        
//                        JTextField textField = new JTextField();
//                        if(p.getVal().equalsIgnoreCase(""))
//                            textField.setText(p.getDefVal());
//                        else
//                            textField.setText(p.getVal());
//                        add(textField);
//                    
//                        JTextField textFieldSecondary = new JTextField();
//                        if(p.getSecondaryVal().equalsIgnoreCase(""))
//                            textFieldSecondary.setText(p.getDefSecondaryVal());
//                        else
//                            textFieldSecondary.setText(p.getSecondaryVal());
//                        add(textFieldSecondary);
//
//                    }
//                    else if(ofProp instanceof Function)
//                    {
//                        Function f = (Function) ofProp;
//                        
//                        JLabel label = new JLabel(f.getKey());
//                        if(f.getParams()!=null)
//                        {
//                            ArrayList<Param> params = (ArrayList<Param>) f.getParams();
//                            for(int j=0;j<params.size();j++)
//                            {                                
//                                JTextField textField = new JTextField();
//                                
//                            }
//                        }
//                        
//                    }
//
                }
            }
        }        
    }
    
    PatchNode pNode;
    Project pr;
    String patchSelected;
    /**
     * Creates new form PatchBasicInfo
     */
    public PatchFieldInfo(PatchNode pNode, Project pr) {
        initComponents();
        setBorder(BorderFactory.createTitledBorder("K"));
        this.pNode = pNode;
        this.pr = pr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox(ProjectUtils.getFieldPatches());
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new SubPanel();

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PatchFieldInfo.class, "PatchFieldInfo.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        patchSelected = (String) jComboBox1.getSelectedItem();
        //jPanel1 = new SubPanel();
        ((SubPanel)jPanel1).removeAll();
        ((SubPanel)jPanel1).repaint();
        ((SubPanel)jPanel1).initComponents();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
